version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: statec-db
    environment: 
      MYSQL_ROOT_PASSWORD:  testStatec
    volumes:
      - ./prisma/DB/Data:/var/lib/mysql
    restart: always
  api:
    build: "."
    container_name: node-container
    restart: always
    environment:
      SECRET:  testStatec
      DATABASE_URL: mysql://root:testStatec@statec-db:3306/statec
    volumes:
      - .:/home/node/app
    ports: 
      - "3000:3000"
    depends_on: 
      - db